# Generated by Django 5.0.6 on 2024-06-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patchwork', '0047_add_database_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='dependencies',
            field=models.ManyToManyField(
                blank=True,
                help_text='Optional dependencies on this patch.',
                related_name='dependents',
                related_query_name='dependent',
                to='patchwork.series',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='parse_dependencies',
            field=models.BooleanField(
                default=False,
                help_text='Enable parsing dependencies on patches and cover '
                'letters.',
            ),
        ),
    ]
